repo_name: mike-test
repo_tag: alpine-3
target_platforms:
  - "linux/arm64"
  - "linux/amd64"

# If NO targets is specified, use the defaults. Useful for single account/region deployment
# If PART of the targets are missing, complete using the defaults
targets:
  # Inherits default region and role
  - aws_account_id: 633681147894

#  # Explicit
  - aws_account_id: 633681147894
    aws_region: ap-northeast-1  # Tokyo Japan
    aws_role_name: github-actions-cross-account