aws_region: ap-northeast-1  # Japan
aws_role_name: mike-ecr-query
aws_account_id: 637423413210  # bcp-test
repo_name: mike-cross-account-test
repo_tag: alpine
target_platforms:
  - "linux/arm64"
  - "linux/amd64"