name: CI

on: push

jobs:
  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Run tests with coverage
        run: go test ./... -coverprofile=coverage.out -covermode=atomic

      - name: Summary coverage
        run: go tool cover -func=coverage.out | tail -n 1

  validate-goreleaser-conf:
    name: Validate go-releaser conf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Validate
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: check

  dry-run:
    name: Dry run
    runs-on: ubuntu-latest
    if: github.ref_name != 'main'
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: "arn:aws:iam::${{ vars.BASE_AWS_ACCOUNT }}:role/${{ vars.BASE_IAM_ROLE_NAME }}"
          aws-region: ${{ vars.BASE_REGION }}

      - name: Build target JSON
        env:
          IMAGE_DIRECTORY: images
          VERSION: v1.0.0
        run: |
          wget --quiet --output-document=ecr-image-checker https://github.com/michaelprice232/ecr-image-checker/releases/download/${{ env.VERSION }}/ecr-image-checker_Linux_x86_64
          chmod +x ecr-image-checker
          ./ecr-image-checker >> "$GITHUB_ENV"

      - name: Pretty print JSON
        run: echo $targets | jq